# Generated by Django 5.2.5 on 2025-08-23 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_productgalery'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productgalery',
            options={'verbose_name': 'productgallery', 'verbose_name_plural': 'product gallery'},
        ),
    ]
