# Generated by Django 5.2.5 on 2025-08-16 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0001_initial'),
        ('shop', '0003_alter_variation_variation_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='variations',
            field=models.ManyToManyField(blank=True, to='shop.variation'),
        ),
    ]
